# Setup
title: EGHYA
url: https://vanchesv.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-GPD6K1RZ9H

# Specify the author for blog posts
author:
  name: Iván Ortega
  url: https://twitter.com/elvanches
  email: vanchesv@protonmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Publicaciones
    url: /archive

  - title: Proyecto
    url: /about

  - title: Contacto
    url: /contacto

  - title: Avisos
    url: /avisos